### PR TITLE
chore: Configure pre-commit, update the justfile

### PR DESCRIPTION
**Pull request by aborgna-q**
Setups `pre-commit` instead of the ad-hoc `.github/pre-commit` file, and cleans up the `just` recipes.

The main benefit of this is to avoid running both codebase tests on each commit, since `pre-commit` filters the required checks based on the modified files.

Updates `DEVELOPMENT.md` with the new commands. It should be a bit more straightforward now.

drive-by: Fixes for the `trailing-whitespace` and `end-of-file-fixer` hooks.

### CODE REVIEW

**Review by cqc-alec — COMMENTED** [review]
I ran `just check` on this branch and got a couple of errors:
```
(env) alec:~/r/hugr$ just check
poetry run pre-commit run --all-files
[INFO] Initializing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy:pydantic.
[INFO] Installing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check that executables have shebangs.....................................Failed
- hook id: check-executables-have-shebangs
- exit code: 1

specification/schema/serialization.md: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x specification/schema/serialization.md`
  If on Windows, you may also need to: `git add --chmod=-x specification/schema/serialization.md`
  If it is supposed to be executable, double-check its shebang.

check for merge conflicts................................................Passed
check toml...............................................................Passed
check vcs permalinks.....................................................Passed
check yaml...............................................................Passed
detect private key.......................................................Passed
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing specification/schema/hugr_schema_v1.json
Fixing specification/schema/hugr_schema_v0.json

trim trailing whitespace.................................................Passed
fix utf-8 byte order marker..............................................Passed
mixed line ending........................................................Passed
check python ast.........................................................Passed
check docstring is first.................................................Passed
debug statements (python)................................................Passed
ruff.....................................................................Passed
ruff-format..............................................................Passed
mypy.....................................................................Passed
cargo format.............................................................Passed
cargo check..............................................................Passed
cargo test...............................................................Passed
cargo clippy.............................................................Passed
error: Recipe `check` failed on line 13 with exit code 1
```
Should we fix these before merging?

**Comment by aborgna-q** [comment]
Done.
It may be problematic that we have extra tests here that are not ran in CI (`end-of-file-fixer` and `trailing-whitespace` are the most problematic).
Should I disable them?

**Review by cqc-alec — APPROVED** [review]
Happy to keep or disable those checks.

**Comment by aborgna-q** [comment]
Let's leave them for now, we can always disable them if they become annoying

**Pull request merged**
