### PR TITLE
feat!: Merge `Value` into `Const`

### LINKED ISSUE #874: Get rid of `Value`
`Const`s are defined as `Values` plus a concrete type.

The difference between both types is confusing, specially at the API level.
In practice, most of the times that `Value` is used we do already know their `Type`.

This issue proposes either making `Value` private, or merging it directly with `Const`.

### PR DESCRIPTION
**Pull request by aborgna-q**
`Const` was a struct with a `Value` + a defined type. In practice, the only `Value` that couldn't report its full type was `Sum`.

This PR merges the two structs, adding an explicit `sum_type` to the sum variant.

Also:

- Removes `Type::check_type`, as this is now unnecessary. 
- Splits and clarifies the type check and constant errors;
  `SumTypeError` is not a `ConstTypeError` is not a `CustomCheckFailure`.
  - Adds contexts to those errors, so we get better messages.
- `CustomConst` is now accessible from `::ops::custom` instead of `::values`.

This change breaks the serialisation format.

Closes #874.

BREAKING CHANGE: Removed `Value`, merged into `Const`

### CODE REVIEW

**Comment by aborgna-q** [comment]
The PR is ready, but I'll try to split it a bit

**Comment by aborgna-q** [comment]
Added an ad-hoc `get_const_function_type` in lieu of #880, while we decide on that.

**Comment by doug-q** [comment]
I think the serialisation schema should be changing because the serialisation of const nodes has changed? 

We have already bumped the serialisation version to V1 since the last release, so it is fine to change the V1 schema. If we hadn't bumped since the last release this would necessitate bumping.

**Comment by aborgna-q** [comment]
Yes, here's the new encoding for an (extension) `usize`:

```json
{
  "v": "Extension",
  "c": [
    {
      "c": "ConstUsize",
      "value": 257
    }
  ]
}
```

And for a `[float, usize] + []` const:

```json
{
  "v": "Sum",
  "tag": 0,
  "values": [
    {
      "v": "Extension",
      "c": [
        {
          "c": "ConstUsize",
          "value": 257
        }
      ]
    },
    {
      "v": "Extension",
      "c": [
        {
          "c": "CustomSerialized",
          "typ": {
            "t": "Opaque",
            "extension": "arithmetic.float.types",
            "id": "float64",
            "args": [],
            "bound": "C"
          },
          "value": 5.1,
          "extensions": [
            "arithmetic.float.types"
          ]
        }
      ]
    }
  ],
  "typ": {
    "s": "General",
    "rows": [
      [
        {
          "t": "I"
        },
        {
          "t": "Opaque",
          "extension": "arithmetic.float.types",
          "id": "float64",
          "args": [],
          "bound": "C"
        }
      ],
      []
    ]
  }
}
```

**Comment by aborgna-q** [comment]
I updated the serialization schema manually (merging the json generated by https://github.com/CQCL/guppylang/pull/172 with the local changes).
Hopefully we can improve this process in the future (see https://github.com/CQCL/guppylang/issues/173).

**Review by doug-q — APPROVED** [review]
Awesome, just a few nits

**Pull request merged**
