### PR TITLE
refactor: Default more functions to using open_extensions

### PR DESCRIPTION
**Pull request by croyzor**
A combined version of #616 #617 and #618

### CODE REVIEW

**Review by acl-cqc — COMMENTED** [review]
This looks pretty good, but I've been prodding around here myself too and discovering how much of a maze these various methods are :-(. Does this make `add_op_with_parent` also use `open_extensions`?

**Comment by acl-cqc** [comment]
> Does this make `add_op_with_parent` also use `open_extensions`?

No, it doesn't :(. So I think it's non-obvious, indeed counterintuitive, that which `add_op`/`add_node` function you use, changes what `Option<ExtensionSet>` you get. I think we should probably focus on figuring out why using `open_extensions` everywhere doesn't work.

**Comment by croyzor** [comment]
`add_op_with_parent` still uses `pure`, or there'd be no reason to change the implementation of `any_block_builder`.
Still need to investigate what needs done to update `add_op_with_parent`, unfortunately

**Comment by acl-cqc** [comment]
Superceded by #622

**Pull request closed without merging**
